Add SPI support for MS5611 driver
emlid/Navio2 pull request #34
Opened 2018-02-26 14:57 UTC by IgorAnohin

Hello!
I added SPI support for MS5611.

2018-02-26 15:10 UTC, staroselskii requested changes

2018-02-26 15:10 UTC, staroselskii commented on Python/navio/ms5611.py
> +		def WriteReg(self, reg_address, data = 0x00):
write_register

2018-02-26 15:10 UTC, staroselskii commented on Python/navio/ms5611.py
> +		def ReadRegs(self, reg_address, length=3):
read_registers

2018-02-26 15:10 UTC, staroselskii commented on Python/navio/ms5611.py
> +	class SPI_interface():
SPIDevice

2018-02-26 15:10 UTC, staroselskii commented on Python/navio/ms5611.py
> +	class I2C_interface():
I2CDevice

2018-02-26 15:10 UTC, staroselskii commented on Python/navio/ms5611.py
> +		def WriteReg(self, reg_address, device_address = None):
write_register

2018-02-26 16:02 UTC, IgorAnohin commented
I think, that now names more valid

2018-02-26 16:27 UTC, staroselskii approved these changes

2018-02-27 11:38 UTC, IgorAnohin commented
I think, that 'device' - better name for SPI and I2C, than flag.

2018-05-03 15:56 UTC, merged